- src/nyx/features/aabb.h
> added header to fix build issue.

- src/nyx/image_loader.cpp
- src/nyx/image_loader.h
- src/nyx/phase1.cpp
- src/nyx/phase2.cpp
Added strip Tiff file reading capability. 
Now, ImageLoader class will check whether a file is tiled or not and based on that instantiate either GrayScaleTileTiffLoader or GrayScaleStripTiffLoader.
> Strip reader

- .github/workflows/publish_docker.yml
- Dockerfile
- src/nyx/version.h
- Updated Dockerfile to use bullseye instead of buster (fix Glibc issue)
- Added latest tag to docker image
- Version bump
> Docker image fix

- src/nyx/omezarr.h
Changing how to query zarr data set size and chunk size (as per conversation with Nick)
> update zarr metadata parsing

- .github/workflows/build_and_test_mac.yml
- .github/workflows/build_and_test_ubuntu.yml
- .github/workflows/build_and_test_windows.yml
- CMakeLists.txt
- README.md
- ci-utils/envs/conda_cpp.txt
- src/nyx/gpu/image_moments.cu
- tests/CMakeLists.txt
- Add conda installation info
- Reorder "Nested Features" documentation
- Fix CUDA build issue for Windows
- Add default CUDA_ARCH for versions that are not explicitly supported
> Documentation update

- src/nyx/features/ellipse_fitting.cpp
Add nontrivial ellipse fitting calculation.
> Nontrivial ellipse fitting calculation

- .github/workflows/build_wheels.yml
This PR reduces the CI time from ~1hr 10 mins to ~30 mins.
> Added cibw_build to matrix for more parallelism

- src/nyx/environment.h
- src/nyx/python/new_bindings_py.cpp
- src/nyx/python/nyxus/nyxus.py
- tests/python/test_nyxus.py
Changing Gabor feature defaults via Python API
> POL2943 gabor perf tuneup 3

- README.md
- docs/source/cmdline_and_examples.rst
- src/nyx/environment.h
- src/nyx/features/gabor.cpp
- src/nyx/features/gabor.h
- src/nyx/python/new_bindings_py.cpp
- src/nyx/python/nyxus/nyxus.py
- tests/python/test_nyxus.py
- Add get_params method that returns dictionary of parameters mapped to their values
- Add set_params method that takes in keyword arguments to set any parameter of Nyxus (environment and Gabor parameters)
-  Update constructor to take in Gabor parameters
- Update name of customize_gabor_feature to set_gabor_feature_params
- Add unit tests for getting and setting parameters
> Getters and setters for parameters and Gabor paramaters

- ci-utils/install_prereq_linux.sh
Will revert once my [PR](https://github.com/DraconPern/fmjpeg2koj/pull/15/files) gets merged to `fmjpeg2koj` repo
> Temporary patch to fix fmjpeg2k CMake issue

- src/nyx/environment.cpp
- src/nyx/environment.h
- src/nyx/features/glcm.cpp
- src/nyx/features/glcm.h
- src/nyx/features/gldm.cpp
- src/nyx/features/gldm.h
- src/nyx/features/gldzm.cpp
- src/nyx/features/gldzm.h
- src/nyx/features/glrlm.cpp
- src/nyx/features/glrlm.h
- src/nyx/features/glszm.cpp
- src/nyx/features/glszm.h
- src/nyx/features/ngldm.cpp
- src/nyx/features/ngldm.h
- src/nyx/features/ngtdm.cpp
- src/nyx/features/ngtdm.h
- src/nyx/featureset.h
- src/nyx/output_2_buffer.cpp
- src/nyx/output_2_csv.cpp
- src/nyx/python/new_bindings_py.cpp
> POL3115 case insensitive feature names

- src/nyx/featureset.cpp
Got rid of redundant find() in a map
> POL3115-faster-feature-name-to-code

- .github/workflows/build_and_test_mac.yml
- .github/workflows/build_and_test_ubuntu.yml
- .github/workflows/build_and_test_windows.yml
- .github/workflows/build_wheels.yml
- .github/workflows/publish_pypi.yml
- CMakeLists.txt
- README.md
- ci-utils/envs/conda_cpp.txt
- ci-utils/envs/conda_py.txt
- ci-utils/find_pyarrow.py
- ci-utils/install_prereq_linux.sh
- ci-utils/install_prereq_win.bat
- docs/source/cmdline_and_examples.rst
- pytest.ini
- setup.py
- src/nyx/arrow_output.h
- src/nyx/environment.cpp
- src/nyx/environment.h
- src/nyx/helpers/helpers.h
- src/nyx/main_nyxus.cpp
- src/nyx/output_writers.h
- src/nyx/python/new_bindings_py.cpp
- src/nyx/python/nyxus/nyxus.py
- src/nyx/python/table_caster.h
- src/nyx/results_cache.h
- tests/python/test_nyxus.py
- Add support for writing to Apache Arrow IPC and Parquet files from the CLI and Python API
- Add documentation for writing to Arrow
- Add unit tests for writing to Arrow
> Apache Arrow support

- .github/workflows/publish_docker.yml
Cleaning disk space on the container so that the build continues
[Ref](https://github.com/actions/runner-images/issues/2840)
> Update docker build

- .github/workflows/build_wheels.yml
- .github/workflows/publish_pypi.yml
- ci-utils/install_prereq_win.bat
- Add Arrow build from source for Windows PyPI wheels
- Add install step for Boost for Thrift
> Windows PyPI wheels with Arrow enabled

- .github/workflows/build_cuda11_wheels.yml
- .github/workflows/build_cuda12_wheels.yml
- .github/workflows/publish_cuda11_pypi.yml
- .github/workflows/publish_cuda12_pypi.yml
- ci-utils/install_cuda11_yum.sh
- ci-utils/install_cuda12_yum.sh
- ci-utils/install_cuda_windows.ps1
- ci-utils/install_cuda_yum.sh
- Add Github Actions to build CUDA enabled Windows wheels for PyPI
- Freeze patch version for Linux CUDA wheels
- Combine script for installing CUDA 11 and CUDA 12 on Linux
> Add Github Actions to build CUDA enabled Windows wheels for PyPI

- src/nyx/feature_mgr.h
- src/nyx/feature_mgr_init.cpp
- src/nyx/features/gabor.cpp
- src/nyx/features/gabor.h
- src/nyx/features/gabor_nontriv.cpp
- src/nyx/gpu/gabor.cu
- src/nyx/gpu/gabor.cuh
- src/nyx/main_nyxus.cpp
What's in this PR:
(1) fixed Gabor for CPU
(2) accelerated Gabor for GPGPU
What's not in the PR:
-- Gabor score calculation remains CPU-side because the whole approach may soon be replaced with Cellprofiler's one.
> Yet another GPU performance update 

- tests/python/test_nyxus.py
- Fix error thrown by pyarrow when reading parquet file in tests
> Fix pyarrow error in tests

- src/nyx/features/focus_score.cpp
- src/nyx/features/focus_score.h
- src/nyx/python/nyxus/nyxus.py
- Add nontrivial implementation of Focus Score
- Add ram_limit parameter to ImageQuality class now that it has nontrivial features
> Add nontrivial Focus Score implementation for Image Qaulity

- .github/workflows/build_cuda11_wheels.yml
- .github/workflows/build_cuda12_wheels.yml
- .github/workflows/build_wheels.yml
- .github/workflows/publish_cuda11_pypi.yml
- .github/workflows/publish_cuda12_pypi.yml
- .github/workflows/publish_pypi.yml
- ci-utils/install_prereq_linux.sh
- ci-utils/install_prereq_win.bat
- update boost location
- drop python 3.8
> chore: Update CI

- tests/CMakeLists.txt.gtest
- tests/python/test_nyxus.py
- CMake version update
- Skip failing tests (std::async issue) in Python 3.12
> Fix various CI Issues
